name: I Can Do More
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Say The Words
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eef3f6'
    - '#bccbd2'
    - '#7d94a4'
    - '#6c5e51'
    - '#3f3e44'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
