name: I Can Do More
favicon: null
layout_spectrum: 0.74581
typography_spectrum: 0.73324
title: Say The Words
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141600'
    - '#6f7825'
    - '#a89e22'
    - '#fdfca0'
    - '#57b51e'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
