name: I Can Do More
favicon: null
layout_spectrum: 0.76283
typography_spectrum: 1
title: Say The Words
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b2936'
    - '#f2f3f8'
    - '#a9c4d7'
    - '#7a5252'
    - '#827262'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
